awk '/\/\/ Draw outer glow and globe background/ {
    print "                    // Outer atmosphere glow"
    print "                    drawCircle("
    print "                        brush = Brush.radialGradient("
    print "                            colors = listOf(Color(0xFF81D4FA).copy(alpha = 0.4f), Color.Transparent),"
    print "                            center = center,"
    print "                            radius = radius * 1.2f"
    print "                        ),"
    print "                        radius = radius * 1.2f,"
    print "                        center = center"
    print "                    )"
    print "                    "
    print "                    // Ocean base (realistic blue with top-left highlight)"
    print "                    drawCircle("
    print "                        brush = Brush.radialGradient("
    print "                            colors = listOf(Color(0xFF4FC3F7), Color(0xFF0288D1), Color(0xFF01579B), Color(0xFF000000)),"
    print "                            center = Offset(center.x - radius * 0.4f, center.y - radius * 0.4f),"
    print "                            radius = radius * 1.6f"
    print "                        ),"
    print "                        radius = radius,"
    print "                        center = center"
    print "                    )"
    print "                    "
    print "                    // Rotating Longitude Lines"
    print "                    for (lon in 0..360 step 30) {"
    print "                        val path = androidx.compose.ui.graphics.Path()"
    print "                        var isFirst = true"
    print "                        for (lat in -90..90 step 5) {"
    print "                            val latRad = Math.toRadians(lat.toDouble())"
    print "                            val lonRad = Math.toRadians(lon.toDouble() + rotationAngle)"
    print "                            val x = cos(latRad) * sin(lonRad)"
    print "                            val y = -sin(latRad)"
    print "                            val z = cos(latRad) * cos(lonRad)"
    print "                            if (z > -0.1) {"
    print "                                val px = center.x + (x * radius).toFloat()"
    print "                                val py = center.y + (y * radius).toFloat()"
    print "                                if (isFirst) {"
    print "                                    path.moveTo(px, py)"
    print "                                    isFirst = false"
    print "                                } else {"
    print "                                    path.lineTo(px, py)"
    print "                                }"
    print "                            } else {"
    print "                                isFirst = true"
    print "                            }"
    print "                        }"
    print "                        drawPath(path, color = Color.White.copy(alpha = 0.15f), style = Stroke(width = 1.dp.toPx()))"
    print "                    }"
    print ""
    print "                    // Rotating Latitude Lines"
    print "                    for (lat in -80..80 step 20) {"
    print "                        val path = androidx.compose.ui.graphics.Path()"
    print "                        var isFirst = true"
    print "                        for (lon in 0..360 step 5) {"
    print "                            val latRad = Math.toRadians(lat.toDouble())"
    print "                            val lonRad = Math.toRadians(lon.toDouble() + rotationAngle)"
    print "                            val x = cos(latRad) * sin(lonRad)"
    print "                            val y = -sin(latRad)"
    print "                            val z = cos(latRad) * cos(lonRad)"
    print "                            if (z > -0.1) {"
    print "                                val px = center.x + (x * radius).toFloat()"
    print "                                val py = center.y + (y * radius).toFloat()"
    print "                                if (isFirst) {"
    print "                                    path.moveTo(px, py)"
    print "                                    isFirst = false"
    print "                                } else {"
    print "                                    path.lineTo(px, py)"
    print "                                }"
    print "                            } else {"
    print "                                isFirst = true"
    print "                            }"
    print "                        }"
    print "                        drawPath(path, color = Color.White.copy(alpha = 0.15f), style = Stroke(width = 1.dp.toPx()))"
    print "                    }"
    print "                    "
    print "                    // Inner shadow for 3D sphere effect"
    print "                    drawCircle("
    print "                        brush = Brush.radialGradient("
    print "                            colors = listOf(Color.Transparent, Color(0xAA000000)),"
    print "                            center = center,"
    print "                            radius = radius"
    print "                        ),"
    print "                        radius = radius,"
    print "                        center = center"
    print "                    )"
    
    in_block = 1
    next
}
/\/\/ Draw dots for added cities/ {
    in_block = 0
}
!in_block { print }
' app/src/main/java/com/example/ui/screens/worldclock/WorldClockScreen.kt > temp.kt && mv temp.kt app/src/main/java/com/example/ui/screens/worldclock/WorldClockScreen.kt
